// 보충교재 16 — Gârleanu–Pedersen 동적 거래 모델 (독립 보충자료)
// 원 논문: Gârleanu·Pedersen, "Dynamic Trading with Predictable Returns and Transaction Costs", JF 68(6) 2013
// 손계산·시뮬레이션 숫자는 gp_art.py 가 직접 계산한 값이다(_art/gp/sim_compare.txt).
// 실행: NODE_PATH=/Users/keerhee/Project/node_modules node gp_deck.js
const fs = require("fs"), path = require("path");
const { build, C } = require("./primer_deck.js");

const OUTDIR = "보충교재/16_Garleanu_Pedersen모델";
fs.mkdirSync(path.join(__dirname, "..", OUTDIR), { recursive: true });

module.exports = {
  art: "gp",
  out: `${OUTDIR}/GP_동적거래모델_조준점과부분이동_ZeroOne.pptx`,
  eyebrow: "연기금 운용전략과 성과평가 · 보충교재 16 · Gârleanu–Pedersen 모델",
  coverTitle: "Gârleanu–Pedersen\n동적 거래 모델",
  coverSub: "예측할 수 있는 수익과 거래비용이 함께 있을 때의 최적 거래 규칙",
  chain: ["신호", "조준점", "부분 이동", "순효용"],

  agendaTitle: "다섯 구획으로 모델을 처음부터 끝까지 읽습니다",
  agenda: [
    { num: "01", title: "문제", kicker: "좋은 신호, 비싼 거래",
      desc: "목표를 좇는 비용 · 신호의 반감기 · 이차 비용" },
    { num: "02", title: "모델", kicker: "식 네 개",
      desc: "신호 · 소멸 · 거래비용 · 목적함수" },
    { num: "03", title: "해", kicker: "두 원칙",
      desc: "부분 이동(a/λ) · 조준점 · 신호별 반영 비율" },
    { num: "04", title: "숫자로 확인", kicker: "손계산 · 시뮬레이션 · 실증",
      desc: "세 기간 경로 · 네 전략 비교 · 상품선물" },
    { num: "05", title: "연기금에 쓰기", kicker: "W07과 이어서",
      desc: "무거래 구간과의 차이 · 대형 전환 · RL의 기준선" },
  ],
  agendaBanner: "원 논문: Gârleanu·Pedersen, Journal of Finance 68(6), 2013",

  slides: [
    { type: "cards", title: "이 모델은 동적 운용의 기준 모델입니다",
      cards: [{ cap: "CLOSED FORM", title: "답이 공식이다",
                bullets: ["공식 두 줄이 최적 규칙", "학습·탐색이 필요 없다", "숫자 넣으면 바로 계산"] },
              { cap: "INTUITION", title: "직관이 분명하다",
                bullets: ["조준점을 앞에 둔다", "간격의 일부만 메운다", "위원회에 설명된다"] },
              { kind: "lime", cap: "BENCHMARK", title: "다른 방법의 잣대",
                bullets: ["MPO·RL이 먼저 재현할 답", "재현 못 하면 신뢰 불가", "W07 3교시의 기준선"] }],
      h: 3.52,
      punch: ["예측(신호)과 거래(정책)를 깔끔하게 나눠 푼 첫 모델입니다.",
              { text: "Aim in front of the target, and trade partially toward the current aim.", color: C.red }] },

    // ───────────────────────── 01 ─────────────────────────
    { type: "divider", num: "01", title: "문제",
      sub: "좋은 신호가 있어도 그대로 좇으면 비용으로 손해를 봅니다" },

    { type: "fig", file: "dilemma.png",
      title: "목표를 매번 그대로 좇으면 사고팔기를 끝없이 반복합니다",
      punch: ["빠른 신호가 목표를 매 기간 흔들고, 목표 추종은 그 흔들림을 전부 거래로 옮깁니다.",
              { text: "같은 신호로 GP는 거래량을 약 3분의 1로 줄입니다.", color: C.red }] },

    { type: "cards", title: "흔히 쓰는 세 가지 답은 모두 한쪽을 버립니다",
      cards: [{ cap: "답 ①", title: "매번 목표로",
                bullets: ["신호는 다 쓴다", "비용이 신호 이득을 삼킨다", "빠른 신호일수록 손해"] },
              { cap: "답 ②", title: "정해 둔 비중 고정",
                bullets: ["비용은 거의 없다", "신호를 통째로 버린다", "W07 2교시 캘린더 방식"] },
              { kind: "dark", cap: "답 ③", title: "목표를 향해 조금씩",
                bullets: ["방향은 맞다", "그런데 어디를 향해?", "얼마나 빨리?"] }],
      h: 3.52,
      punch: [{ text: "GP는 답 ③에 두 숫자를 공식으로 줍니다 — 어디를 겨눌지(조준점), 얼마나 갈지(a/λ).", color: C.red }] },

    { type: "eq", file: "eq_markowitz.png", cap: "비용이 없을 때의 최적 보유 — Markowitz 목표",
      title: "비용이 없으면 답은 매 기간의 Markowitz 목표입니다",
      cards: [{ cap: "f", title: "지금의 신호" },
              { cap: "B", title: "신호 → 기대수익" },
              { cap: "γΣ", title: "위험회피 × 공분산" },
              { kind: "lime", cap: "x*", title: "오늘의 목표 보유" }],
      punch: [{ text: "기대수익이 두 배면 보유도 두 배, 위험을 두 배 싫어하면 보유는 절반입니다.", color: C.teal },
              { text: "신호가 매 기간 바뀌므로 이 목표도 매 기간 움직입니다.", color: C.red }] },

    { type: "fig", file: "decay.png",
      title: "신호마다 사라지는 속도가 다릅니다",
      punch: ["φ는 한 기간에 사라지는 비율이고, 반감기는 약 0.69 ÷ φ 기간입니다.",
              { text: "금방 사라질 신호를 좇아 거래하면, 도착할 무렵엔 비용만 남습니다.", color: C.red }] },

    { type: "fig", file: "quad_cost.png",
      title: "큰 주문은 한 번에 많이 살수록 단위 비용이 커집니다",
      punch: ["많이 살수록 가격이 불리하게 움직여 단위 비용까지 커집니다(시장충격).",
              { text: "그래서 나눠 사는 편이 싸다 — 실증은 제곱근 법칙, GP는 제곱 비용으로 근사", color: C.red }] },

    { type: "table", title: "비용 구조가 최적 행동의 모양을 정합니다",
      head: ["", "비례 비용", "이차 비용"],
      rows: [["원천", "수수료 · 호가 스프레드", "시장충격 (큰 주문)"],
             ["작은 거래", "그대로 비용 → 안 한다", "거의 0 → 조금씩 한다"],
             ["최적 행동", "무거래 구간 (밖이면 경계까지)", "매번 간격의 일정 비율"],
             ["대표 모델", "Davis–Norman (1990)", "Gârleanu–Pedersen (2013)"],
             ["연기금에서", "소형 · 정기 리밸런싱", "대형 전환 · 전술 신호 운용"]],
      widths: [2.20, 4.80, 4.79], rowH: 0.64, emph: 2,
      note: "※ 두 비용이 섞이면 닫힌 해가 없어 다기간 최적화(MPO)나 강화학습이 필요합니다(5부).", noteY: 5.98 },

    // ───────────────────────── 02 ─────────────────────────
    { type: "divider", num: "02", title: "모델",
      sub: "식 네 개 — 수익은 신호로, 신호는 소멸로, 비용은 이차식으로, 목적은 하나로" },

    { type: "eq", file: "eq_signal.png", cap: "① 수익은 신호로 예측된다",
      title: "다음 기간 초과수익의 일부는 지금의 신호로 예측됩니다",
      cards: [{ cap: "r(t+1)", title: "다음 기간 초과수익" },
              { cap: "f(t)", title: "신호 여러 개" },
              { cap: "B", title: "신호의 예측력" },
              { kind: "lime", cap: "u", title: "예측 못 하는 잡음" }],
      punch: [{ text: "신호 예: 5일 수익률(단기 반전), 1년 수익률(모멘텀), 5년 수익률(장기 반전), 밸류·금리차.", color: C.teal },
              { text: "잡음 u가 대부분입니다. 신호는 평균을 조금 기울일 뿐입니다.", color: C.red }] },

    { type: "eq", file: "eq_decay.png", cap: "② 신호는 평균으로 되돌아간다",
      title: "신호는 매 기간 일정 비율씩 사라집니다",
      cards: [{ cap: "Φ", title: "소멸 속도" },
              { cap: "φ 크다", title: "빨리 사라진다" },
              { cap: "φ 작다", title: "오래 남는다" },
              { kind: "lime", cap: "ε", title: "새 정보" }],
      punch: [{ text: "원 논문 실증의 반감기: 5일 신호 약 2.4일, 1년 신호 약 206일, 5년 신호 약 700일.", color: C.teal },
              { text: "이 속도 차이가 뒤에서 신호마다 다른 대접을 받는 이유가 됩니다.", color: C.red }] },

    { type: "eq", file: "eq_cost.png", cap: "③ 거래비용은 거래량의 이차식",
      title: "거래비용은 거래량의 제곱으로 근사합니다",
      cards: [{ cap: "Δx", title: "이번 기간 거래량" },
              { cap: "λ", title: "비용 계수 하나" },
              { cap: "Σ", title: "위험할수록 비싸다" },
              { kind: "lime", cap: "Λ = λΣ", title: "풀이를 닫는 가정" }],
      punch: [{ text: "Λ = λΣ는 ‘위험한 자산일수록 충격도 크다’는 현실적 가정이면서 해를 한 줄로 만드는 열쇠입니다.", color: C.red }] },

    { type: "eq", file: "eq_obj.png", cap: "④ 목적함수 — 수익 − 위험 벌점 − 거래비용, 할인해 모두 더한다",
      title: "목적은 할인한 ‘수익 − 위험 − 비용’의 합을 최대로 하는 것입니다",
      cards: [{ cap: "x′Bf", title: "기대수익" },
              { cap: "γ/2 · x′Σx", title: "위험 벌점" },
              { cap: "½ Δx′ΛΔx", title: "거래비용" },
              { kind: "lime", cap: "(1 − ρ)^t", title: "할인" }],
      punch: [{ text: "강화학습 말로는 보상 = 수익 − 위험 벌점 − 비용, 할인율 γ 대신 (1 − ρ)입니다.", color: C.teal },
              { text: "오늘의 보유가 내일 거래비용을 바꾸므로 기간들이 서로 묶입니다 — 동적 문제입니다.", color: C.red }] },

    { type: "cards", title: "이 문제는 공식으로 풀리는 드문 동적 문제입니다",
      cards: [{ cap: "목적이 이차식", title: "수익·위험·비용 모두",
                bullets: ["보유와 거래의 제곱까지", "매끄러운 그릇 모양", "꼭대기가 하나"] },
              { cap: "상태 변화가 선형", title: "신호·보유 모두",
                bullets: ["신호는 일정 비율 소멸", "보유는 거래만큼 변화", "곱셈·조건 분기 없음"] },
              { kind: "dark", cap: "그래서", title: "LQ 제어 문제",
                bullets: ["가치함수도 이차식", "최적 규칙은 선형", "a를 이차방정식으로 푼다"] }],
      h: 3.52,
      punch: [{ text: "선형(Linear) 상태 + 이차(Quadratic) 목적 = LQ — 로켓 궤도 제어와 같은 수학입니다.", color: C.red }] },

    // ───────────────────────── 03 ─────────────────────────
    { type: "divider", num: "03", title: "해",
      sub: "조준점을 앞에 두고, 그쪽으로 일부만 이동한다" },

    { type: "fig", file: "two_principles.png",
      title: "최적 규칙은 두 원칙으로 요약됩니다",
      figBottom: 6.34,
      note: "※ 원 논문 요약: “aim in front of the target” 그리고 “trade partially toward the current aim”." },

    { type: "eq", file: "eq_rule.png", cap: "원칙 1 · 부분 이동",
      title: "원칙 1 — 조준점과의 간격 중 일부만 이번에 메웁니다",
      cards: [{ cap: "x(t−1)", title: "어제 보유" },
              { cap: "aim(t)", title: "오늘의 조준점" },
              { cap: "a/λ", title: "거래 속도 (0~1)" },
              { kind: "lime", cap: "x(t)", title: "둘의 가중평균" }],
      punch: [{ text: "거래 속도 a/λ는 숫자 하나이고, 신호가 몇 개든 어떤 종류든 같습니다(Λ = λΣ일 때).", color: C.teal },
              { text: "γ = 1, λ = 2면 a = 1, a/λ = 0.5 — 매번 간격의 절반씩 메웁니다.", color: C.red }] },

    { type: "eq", file: "eq_a.png", cap: "거래 속도를 정하는 a — 이차방정식의 근",
      title: "a는 위험회피 γ와 비용 λ만으로 정해집니다",
      cards: [{ cap: "λ → 0", title: "목표 그대로" },
              { cap: "λ 크다", title: "a/λ ≈ √(γ/λ)" },
              { cap: "γ 크다", title: "더 빨리 메운다" },
              { kind: "lime", cap: "ρ = 0", title: "a² + γa = γλ" }],
      punch: [{ text: "할인이 없으면 a는 a² + γa − γλ = 0의 양의 근입니다. γ = 1, λ = 2 → a = 1.", color: C.teal },
              { text: "위험을 싫어할수록 빨리 메우는 이유: 목표에서 떨어진 동안 원치 않는 위험을 지기 때문입니다.", color: C.red }] },

    { type: "fig", file: "trade_rate.png",
      title: "비용이 클수록 천천히, 위험을 싫어할수록 빨리 이동합니다",
      punch: ["λ가 10배 커질 때마다 속도는 대략 √10 ≈ 3분의 1로 느려집니다(λ가 큰 쪽).",
              { text: "비용이 아무리 커도 속도는 0이 되지 않습니다. 이차 비용은 거래를 멈추게 하지 않습니다.", color: C.red }] },

    { type: "eq", file: "eq_aim_sum.png", cap: "원칙 2 · 조준점 = 미래 목표들의 가중평균",
      title: "원칙 2 — 오늘 목표가 아니라 앞으로의 목표들을 겨눕니다",
      cards: [{ cap: "E[x*(t+τ)]", title: "미래 목표들" },
              { cap: "z(1 − z)^τ", title: "멀수록 가볍게" },
              { cap: "z = γ/(γ + a)", title: "오늘 목표 몫" },
              { kind: "lime", cap: "ρ = 0이면", title: "z = a/λ" }],
      punch: [{ text: "날아가는 새를 쏠 때 총알이 도착할 자리를 겨누는 것과 같습니다.", color: C.teal },
              { text: "거래가 느릴수록(z가 작을수록) 더 먼 미래의 목표까지 조준점에 들어옵니다.", color: C.red }] },

    { type: "fig", file: "aim_weights.png",
      title: "조준점은 앞으로 남아 있을 목표의 크기를 반영합니다",
      punch: ["빠른 신호의 목표는 금방 0으로 줄어 조준점이 0.667, 느린 신호는 거의 그대로 남아 0.952입니다.",
              { text: "같은 오늘 목표 1이라도 신호가 얼마나 오래가느냐에 따라 겨누는 곳이 다릅니다.", color: C.red }] },

    { type: "eq", file: "eq_aim_signal.png", cap: "신호별로 풀어 쓴 조준점",
      title: "조준점은 신호마다 기여분을 1/(1 + φa/γ)만큼 줄입니다",
      cards: [{ cap: "φ = 0.5", title: "0.667만 반영" },
              { cap: "φ = 0.05", title: "0.952 반영" },
              { cap: "a = 0 (비용 0)", title: "모두 1" },
              { kind: "lime", cap: "결과", title: "느린 신호 우대" }],
      punch: [{ text: "비용이 없으면 모든 신호가 똑같이 대접받습니다. 차등은 비용이 있을 때만 생깁니다.", color: C.teal },
              { text: "도착할 무렵 사라질 신호는 비용만 남기므로 덜 반영하는 것이 합리적입니다.", color: C.red }] },

    { type: "fig", file: "signal_weight.png",
      title: "비용이 클수록 빠른 신호를 더 강하게 깎습니다",
      punch: ["비용이 작으면(λ = 0.2) 반감기 1기간 신호도 거의 다 반영합니다.",
              { text: "비용이 크면(λ = 20) 같은 신호를 4분의 1만 반영합니다. 반감기가 길면 비용과 무관하게 거의 1입니다.", color: C.red }] },

    { type: "table", title: "숫자가 바뀌면 규칙이 이렇게 움직입니다",
      head: ["바뀌는 것", "거래 속도 a/λ", "조준점", "직관"],
      rows: [["비용 λ ↑", "느려진다", "느린 신호 쪽으로", "천천히, 멀리 겨눈다"],
             ["위험회피 γ ↑", "빨라진다", "오늘 목표에 가까워짐", "떨어진 동안의 위험이 싫다"],
             ["신호 소멸 φ ↑", "변화 없음", "그 신호 몫이 줄어듦", "곧 사라질 것은 덜"],
             ["할인 ρ ↑", "느려진다", "오늘 목표 쪽", "미래 이득을 덜 친다"]],
      widths: [2.60, 2.60, 3.00, 3.59], rowH: 0.70, emph: 0,
      note: "※ 거래 속도가 신호와 무관하다는 점이 핵심입니다. 신호는 ‘어디로’만, 비용·위험은 ‘얼마나 빨리’만 정합니다.", noteY: 5.98 },

    // ───────────────────────── 04 ─────────────────────────
    { type: "divider", num: "04", title: "숫자로 확인",
      sub: "세 기간 손계산, 20만 기간 시뮬레이션, 원 논문의 상품선물 실증" },

    { type: "table", title: "세 기간 손계산 — Markowitz가 줄일 때 GP는 오히려 삽니다",
      head: ["기간", "Markowitz 목표", "조준점", "GP 보유", "GP 거래"],
      rows: [["1", "200", "161.9", "81.0", "+81.0"],
             ["2", "145", "123.8", "102.4", "+21.4"],
             ["3", "115.2", "102.6", "102.5", "+0.1"]],
      widths: [1.60, 2.60, 2.40, 2.40, 2.79], rowH: 0.66, emph: 1,
      punch: ["γ = 1, λ = 2(a/λ = 0.5), σ² = 1. 빠른·느린 신호가 처음에 100씩 가리키고 기댓값대로 줄어듭니다.",
              { text: "2기간에 Markowitz는 55를 팔지만, GP는 느린 신호가 남을 것을 알고 21을 더 삽니다.", color: C.red }],
      punchY: 4.86 },

    { type: "fig", file: "cost_bars.png",
      title: "세 기간 거래비용은 GP가 약 6분의 1입니다",
      punch: ["조준점 계산: 100 × 0.667 + 100 × 0.952 = 161.9 → 보유는 그 절반 81.0.",
              { text: "비용 지수 = (거래량)²의 합: 목표 추종 43,910, GP 7,012.", color: C.red }] },

    { type: "fig", file: "sim_paths.png",
      title: "GP 보유는 조준점보다도 부드럽게 움직입니다",
      punch: ["조준점이 빠른 신호의 흔들림을 한 번 거르고, 부분 이동이 한 번 더 거릅니다.",
              { text: "그래도 느린 신호가 가리키는 큰 방향은 놓치지 않습니다.", color: C.red }] },

    { type: "fig", file: "sim_compare.png",
      title: "GP는 기대수익을 일부 내주고 순효용을 가장 크게 만듭니다",
      punch: ["목표 추종은 비용이 기대수익의 절반을 넘어 순효용이 음수(−7.2)입니다.",
              { text: "부분 이동 속도를 최적화해도(67.4) 조준점을 쓴 GP(69.8)에 못 미칩니다.", color: C.red }] },

    { type: "cards", title: "원 논문의 상품선물 실증도 같은 결론입니다",
      cards: [{ cap: "DATA", title: "15개 상품선물",
                bullets: ["금속·에너지·농산물", "1996~2009 일별", "신호: 5일·1년·5년 수익률"] },
              { cap: "COSTS", title: "현실적 충격비용",
                bullets: ["Λ = λΣ로 추정", "비용 두 배도 점검", "반감기 2.4·206·700일"] },
              { kind: "lime", cap: "RESULT", title: "비용 차감 후 우위",
                bullets: ["비용 전: 목표 추종이 우위", "비용 뒤: GP가 유의하게 우위", "최선의 정적 전략도 이김"] }],
      h: 3.52,
      punch: ["비용을 무시한 전략은 ‘종이 위의 샤프’가 가장 높지만, 실제로 손에 남는 것은 가장 적습니다.",
              { text: "조준점과 부분 이동은 실제 데이터에서도 비용을 이깁니다.", color: C.red }] },

    // ───────────────────────── 05 ─────────────────────────
    { type: "divider", num: "05", title: "연기금에 쓰기",
      sub: "W07의 글라이드패스 · 리밸런싱 · 강화학습과 이어서" },

    { type: "fig", file: "band_vs_gp.png",
      title: "같은 목표라도 비용 구조가 다르면 최적 행동이 다릅니다",
      punch: ["비례 비용이면 구간 안에서는 가만히(W07 2교시 밴드 리밸런싱, SS2).",
              { text: "이차 비용이면 구간이 없고 매번 조금씩 — 대형 기금의 큰 주문은 이쪽입니다.", color: C.red }] },

    { type: "fig", file: "where_map.png",
      title: "비용 구조와 신호 유무로 쓸 도구가 갈립니다",
      figBottom: 6.34,
      note: "※ 연기금의 실제 비용은 둘이 섞여 있습니다. 작은 조정은 밴드, 큰 전환·전술 신호는 GP, 둘이 얽히면 MPO·RL." },

    { type: "fig", file: "pension_shift.png",
      title: "대형 전환은 나눠 가면 충격비용이 크게 줄어듭니다",
      punch: ["예: 기금 1,000조 원에서 국내주식 5%p(50조 원)를 해외로 옮긴다 — a/λ = 0.35면 6분기에 90%.",
              { text: "한 번에 옮길 때보다 충격비용이 약 5분의 1(0.21)입니다. 대신 늦게 도착하는 동안의 위험을 집니다.", color: C.red }] },

    { type: "cards", title: "W07 케이스의 글라이드패스에도 두 원칙이 적용됩니다",
      cards: [{ cap: "원칙 1로 보면", title: "종점까지 나눠 간다",
                bullets: ["트리거 이후 매년 일부만", "속도는 γ와 충격비용으로", "한 해에 몰면 비용 폭증"] },
              { cap: "원칙 2로 보면", title: "앞을 겨눈다",
                bullets: ["오늘의 H/F가 아니라", "몇 년 뒤의 H/F를 조준", "오래갈 신호만 반영"] },
              { kind: "dark", cap: "한계", title: "모델 밖의 것",
                bullets: ["부채·유동성 제약", "위원회 한도(허용 범위)", "→ MPO나 RL로 확장"] }],
      h: 3.52,
      punch: [{ text: "글라이드패스는 ‘어디로’의 답이고, GP는 ‘얼마나 빨리, 어디를 겨눠’의 답입니다.", color: C.red }] },

    { type: "table", title: "실무에서는 숫자 세 개를 먼저 추정합니다",
      head: ["단계", "할 일", "주의"],
      rows: [["① 신호 반감기 φ", "신호를 AR(1)로 회귀해 소멸 속도 추정", "불안정하면 범위로 두고 민감도 점검"],
             ["② 충격비용 λ", "체결 기록으로 거래량 대비 가격 충격 추정", "시장 스트레스 때 두세 배로"],
             ["③ 위험회피 γ", "목표 변동성·위험예산에서 역산", "IPS의 위험 한도와 맞춘다"],
             ["④ 점검", "세 전략을 같은 비용 조건으로 비교", "회전율 · 비용 · 순효용 세 줄"]],
      widths: [2.50, 5.10, 4.19], rowH: 0.70, emph: 3,
      note: "※ 연기금 TAA, 팩터 틸트, 해외 비중 확대처럼 신호는 있고 주문이 큰 운용에 맞습니다.", noteY: 5.98 },

    { type: "cards", title: "강화학습에게 GP는 먼저 재현해야 할 정답입니다",
      cards: [{ cap: "TESTBED", title: "재현 테스트",
                bullets: ["같은 가정의 합성시장에서", "a/λ = 0.5를 배워 내는가", "0.667 · 0.952를 재현하는가"] },
              { cap: "RL의 자리", title: "공식이 틀리는 곳",
                bullets: ["비례 + 이차 비용 혼합", "한도 · 공매도 금지 제약", "국면에 따라 λ가 바뀔 때"] },
              { kind: "lime", cap: "HYBRID", title: "결합 구조",
                bullets: ["조준점은 공식으로", "RL은 속도만 조절", "해석 가능성을 지킨다"] }],
      h: 3.52,
      punch: [{ text: "GP도 재현 못 하는 RL은 더 어려운 문제에서도 믿을 수 없습니다 — W07 3교시 ‘기준선’.", color: C.red }] },

    { type: "table", title: "GP 이후의 연구는 모델의 가정을 하나씩 풉니다",
      head: ["연구", "무엇을 풀었나", "한 줄 요지"],
      rows: [["GP (2016, JET)", "연속시간 · 일반적 신호·비용", "두 원칙이 일반적 틀에서도 성립"],
             ["Collin-Dufresne 외 (2020)", "유동성 국면 전환", "비용이 커질 국면을 미리 조준에 반영"],
             ["Boyd 외 (2017)", "다기간 볼록 최적화 (MPO)", "제약·혼합 비용을 수치로 푼다"],
             ["RL 포트폴리오 연구", "모형 없이 학습", "GP 재현이 첫 관문 (보충교재 14)"]],
      widths: [3.60, 3.60, 4.59], rowH: 0.70, emph: 3,
      note: "※ 서지: GP(2016) J. Economic Theory 165 · Collin-Dufresne·Daniel·Sağlam(2020) J. Financial Economics · Boyd 외(2017) Foundations and Trends in Optimization.", noteY: 5.98 },

    { type: "table", title: "부분 이동은 스무딩이 아니라 미래를 향한 조준입니다",
      head: ["흔한 오해", "실제"],
      rows: [["이동평균으로 부드럽게 한 것과 같다", "이동평균은 과거(후행), 조준점은 미래(선행)"],
             ["느린 신호가 원래 더 좋다", "비용 0이면 똑같다 — 비용이 있을 때만 차등"],
             ["비용이 크면 거래를 멈춘다", "이차 비용은 속도만 줄인다 — 멈춤은 비례 비용"],
             ["가정이 단순해 실무에 못 쓴다", "두 원칙은 강건하고, 복잡한 방법의 잣대가 된다"]],
      widths: [4.80, 6.99], rowH: 0.70, emph: 0,
      banner: "조준점 = 앞을 본다 · 부분 이동 = 비용을 나눈다", bannerY: 5.96 },

    { type: "table", title: "답을 맞혀 보고 W07 강의본 3교시로 넘어가십시오",
      head: ["스스로 점검", "답", "왜 그런가"],
      rows: [["γ = 1, λ = 2일 때 거래 속도는?", "0.5", "a² + a − 2 = 0 → a = 1"],
             ["φ = 0.5 신호의 반영 비율은?", "0.667", "1 ÷ (1 + 0.5 × 1)"],
             ["비용이 없다면 GP는?", "Markowitz", "a/λ = 1, 모든 신호 반영 1"],
             ["비례 비용뿐이라면?", "무거래 구간", "작은 거래도 그대로 비용"]],
      widths: [4.60, 2.60, 4.59], rowH: 0.70, dy: 0.10,
      punch: [{ text: "넷 다 맞혔다면 W07 강의본 3교시의 ‘기준선’ 장표가 그대로 읽힙니다.", color: C.red }],
      punchY: 5.86, note: "※ 수치 예제는 수업용 가상 값, 시뮬레이션은 컴퓨터로 만든 가상 실험입니다. 실증 요약은 Gârleanu·Pedersen(2013) 6절.", noteY: 6.38 },

    { type: "closing",
      statements: ["과녁의 앞을 조준합니다.",
                   "조준점까지 일부만 이동합니다.",
                   "빠른 신호는 덜, 느린 신호는 더 반영합니다."],
      message: "W07 강의본\n3교시와 함께",
      contacts: ["보충교재 16 · Gârleanu–Pedersen 모델", "보충교재 14 · 강화학습 포트폴리오"],
      note: "※ 원 논문: N. Gârleanu & L. H. Pedersen (2013), Dynamic Trading with Predictable Returns and Transaction Costs, Journal of Finance 68(6), 2309–2340." },
  ],
};

if (require.main === module) build(module.exports);
