// W14 사전학습 — M15 대체투자와 비유동성 · SS3 세금 효율 투자
const { build, C } = require("./primer_deck.js");
module.exports = {
  art: "w14",
  out: "W14_대체투자와비유동성/W14_0_프라이머_대체투자는왜변동성이낮아보일까.pptx",
  eyebrow: "연기금 운용전략과 성과평가 · W14 사전학습",
  coverTitle: "대체투자는 왜\n변동성이 낮아 보일까",
  coverSub: "W14 사전학습 · M15 대체투자와 비유동성 · SS3 세금 효율 투자",
  chain: ["못 파는 값", "낮아 보이는 변동성", "세금 뒤에 남는 것"],
  agendaTitle: "네 구획이면 30분 안에 읽힙니다",
  agenda: [
    { num: "01", title: "돈이 오가는 모양", kicker: "먼저 넣고 나중에 받는다",
      desc: "처음 몇 해 · J 모양" },
    { num: "02", title: "변동성이 낮아 보인다", kicker: "값을 자주 안 매긴다",
      desc: "장부의 값 · 실제의 값" },
    { num: "03", title: "못 파는 값", kicker: "유동성이란 무엇인가",
      desc: "언제 팔 수 있나 · 그 값은 충분한가" },
    { num: "04", title: "세금 떼고 남는 것", kicker: "수익률은 세전 숫자다",
      desc: "어디에 담을까 · 수식 하나" },
  ],
  agendaBanner: "이 덱은 강의를 요약하지 않습니다. 강의 첫 장을 읽을 수 있게 만듭니다.",
  slides: [
    { type: "divider", num: "01", title: "돈이 오가는 모양",
      sub: "주식을 사는 것과는 돈의 흐름부터 다릅니다" },
    { type: "fig", file: "jcurve.png",
      title: "처음 몇 해는 넣기만 하고 나중에야 돌려받습니다",
      punch: ["약속한 돈을 한 번에 넣는 것이 아니라, 부를 때마다 나눠 냅니다.",
              { text: "그래서 처음 몇 해의 성적은 늘 마이너스로 보입니다.", color: C.red }] },
    { type: "divider", num: "02", title: "변동성이 낮아 보이는 까닭",
      sub: "정말 변동성이 낮은 것인지 따져 봐야 합니다" },
    { type: "fig", file: "smoothing.png",
      title: "값을 자주 매기지 않으면 변동성이 낮게 나옵니다",
      punch: ["상장 주식은 날마다 값이 붙지만, 부동산과 사모펀드는 몇 달에 한 번 붙습니다.",
              { text: "그래서 장부에 적힌 변동성이 실제의 절반쯤으로 나옵니다.", color: C.red }] },
    { type: "cards", title: "그러면 두 가지 착시가 함께 생깁니다",
      cards: [{ cap: "착시 1", title: "덜 위험해 보인다",
                bullets: ["변동성이 작게 나온다", "성적표가 좋아 보인다"] },
              { cap: "착시 2", title: "덜 같이 움직여 보인다",
                bullets: ["주식과 무관해 보인다", "나눠 담기 효과가 커 보인다"] },
              { kind: "dark", cap: "그래서", title: "되돌려 놓고 본다",
                bullets: ["매끄러움을 걷어낸다", "그 뒤에 견준다"] }],
      punch: [{ text: "매끄러움을 걷어내면 대체투자의 매력은 줄지만, 그것이 정직한 비교입니다.", color: C.red }] },
    { type: "divider", num: "03", title: "못 파는 값",
      sub: "팔고 싶을 때 팔 수 없다는 것의 값어치입니다" },
    { type: "fig", file: "liquidity.png",
      title: "자산마다 팔 수 있기까지 걸리는 시간이 다릅니다",
      punch: ["예금은 오늘, 상장 주식은 이틀, 사모펀드는 10년 뒤에나 손에 들어옵니다.",
              { text: "그 불편을 견디는 대가로 더 받는 몫이 있어야 하고, 충분한지 따져야 합니다.", color: C.red }] },
    { type: "divider", num: "04", title: "세금 떼고 남는 것",
      sub: "우리가 보는 수익률은 대부분 세금을 떼기 전 숫자입니다" },
    { type: "fig", file: "after_tax.png",
      title: "언제 세금을 떼느냐만 달라도 결과가 갈립니다",
      punch: ["같은 6%인데도, 해마다 떼면 남는 돈이 크게 줄어듭니다.",
              { text: "떼지 않고 굴린 돈이 다시 벌기 때문입니다.", color: C.red }] },
    { type: "eq", file: "equation.png", cap: "세금을 떼고 손에 남는 수익",
      title: "그 차이를 한 줄로 적습니다",
      cards: [{ cap: "r", title: "세금 떼기 전" },
              { cap: "τ", title: "세율" },
              { cap: "1 − τ", title: "손에 남는 비율" },
              { kind: "lime", cap: "r net", title: "실제로 번 몫" }],
      punch: [{ text: "그래서 “무엇을 살까”만큼 “어느 계좌에 담을까”가 중요합니다.", color: C.teal },
              { text: "세금이 많이 붙는 자산일수록 세금이 미뤄지는 계좌에 담습니다.", color: C.red }] },
    { type: "table", title: "이 덱의 말과 강의본의 말을 이어 둡니다",
      head: ["이 덱에서 쓴 말", "강의본이 쓰는 말", "영어"],
      rows: [["처음 넣기만 하는 모양", "J 커브", "J-curve"],
             ["장부 값이 매끄러워 보임", "평활화", "smoothing"],
             ["그 매끄러움을 걷어내기", "역평활화", "unsmoothing"],
             ["못 파는 값", "비유동성 프리미엄", "illiquidity premium"],
             ["어느 계좌에 담을까", "자산 위치", "asset location"]],
      widths: [4.60, 3.40, 3.79], emph: 3,
      banner: "강의본은 가운데 말을 씁니다. 이 표가 둘 사이의 다리입니다." },
    { type: "table", title: "답을 맞춰 보고 강의로 넘어가십시오",
      head: ["강의 전에 답해 볼 것", "답", "왜 그런가"],
      rows: [["처음 몇 해가 마이너스면?", "정상이다", "넣기만 하는 기간이다"],
             ["부동산은 변동성이 낮나?", "그렇게 보일 뿐", "값을 자주 안 매겨서다"],
             ["같은 6%면 같은 결과인가?", "아니다", "언제 세금을 떼느냐가 가른다"]],
      widths: [4.30, 3.10, 4.39], rowH: 0.86, dy: 0.10,
      punch: [{ text: "세 개를 다 맞혔다면 강의본 첫 장이 그대로 읽힙니다.", color: C.red }],
      punchY: 5.86, note: "※ 이 덱의 숫자는 모두 수업용으로 지어낸 예시입니다." },
    { type: "closing",
      statements: ["대체투자는 돈이 오가는 모양부터 다릅니다.",
                   "변동성이 낮아 보이는 것은 값을 자주 안 매겨서이고,",
                   "손에 남는 돈은 세금을 떼고 나서 정해집니다."],
      message: "이제 강의본으로\n넘어가십시오",
      contacts: ["W14 · 대체투자와 비유동성", "W14 · 특별세션 SS3 세금 효율 투자"],
      note: "※ 4교시는 모의 투자위원회입니다. 실제 시장 자료와 정확한 정의는 강의본과 실습데이터 덱에서 다룹니다." },
  ],
};
if (require.main === module) build(module.exports);
