// W15 사전학습 — M16 총자산 접근(TPA) · 종강
const { build, C } = require("./primer_deck.js");
module.exports = {
  art: "w15",
  out: "W15_TPA/W15_0_프라이머_TPA는예산을누구에게주는가.pptx",
  eyebrow: "연기금 운용전략과 성과평가 · W15 사전학습",
  coverTitle: "TPA는 예산을\n누구에게 주는가",
  coverSub: "W15 사전학습 · M16 TPA 총자산 접근 · 종강",
  chain: ["부서별 칸막이", "겹친 베팅", "하나의 위험 예산"],
  agendaTitle: "네 구획이면 30분 안에 읽힙니다",
  agenda: [
    { num: "01", title: "칸막이의 문제", kicker: "각자 최선을 다해도",
      desc: "부서별 예산 · 축구팀 비유" },
    { num: "02", title: "겹친 베팅", kicker: "다른 자산, 같은 위험",
      desc: "무엇을 샀나 vs 무엇을 졌나" },
    { num: "03", title: "하나의 예산", kicker: "아이디어끼리 겨룬다",
      desc: "부서가 아니라 값어치대로" },
    { num: "04", title: "무엇이 어려운가", kicker: "구조를 바꾸는 일",
      desc: "평가와 보상 · 수식 하나" },
  ],
  agendaBanner: "이 덱은 강의를 요약하지 않습니다. 강의 첫 장을 읽을 수 있게 만듭니다.",
  slides: [
    { type: "divider", num: "01", title: "칸막이의 문제",
      sub: "모두가 자기 자리에서 최선을 다하는데도 생기는 일입니다" },
    { type: "fig", file: "soccer.png",
      title: "포지션별 최고를 모은다고 최강팀이 되지는 않습니다",
      punch: ["각자 자기 칸에서 이겨도, 함께 보면 겹치거나 비어 있습니다.",
              { text: "부서를 없애자는 말이 아니라, 예산을 부서가 아니라 아이디어에 준다는 말입니다.", color: C.red }] },
    { type: "divider", num: "02", title: "겹친 베팅",
      sub: "무엇을 샀는지가 아니라 무엇을 졌는지를 봅니다" },
    { type: "fig", file: "overlap.png",
      title: "이름이 다른 자산이 같은 위험을 지고 있습니다",
      punch: ["주식팀도 대체팀도 매크로팀도 결국 “경기가 좋다”에 걸었습니다.",
              { text: "자산 이름으로 나눠 놓으면 이 겹침이 보이지 않습니다.", color: C.red }] },
    { type: "cards", title: "그래서 질문을 바꿉니다",
      cards: [{ cap: "예전 질문", title: "무엇을 샀나",
                bullets: ["주식 · 채권 · 대체", "이름으로 나눈다"] },
              { cap: "바뀐 질문", title: "무엇을 졌나",
                bullets: ["경기 · 금리 · 물가", "위험으로 나눈다"] },
              { kind: "lime", cap: "그러면", title: "겹침이 보인다",
                bullets: ["비어 있는 곳도 보인다", "예산을 옮길 수 있다"] }],
      punch: [{ text: "질문을 바꾸면 같은 포트폴리오가 완전히 다르게 보입니다.", color: C.red }] },
    { type: "divider", num: "03", title: "하나의 예산",
      sub: "부서가 아니라 아이디어가 예산을 놓고 겨룹니다" },
    { type: "fig", file: "budget.png",
      title: "예산은 부서가 아니라 아이디어의 값어치대로 갑니다",
      punch: ["좋은 아이디어면 어느 팀 것이든 예산을 더 가져갑니다.",
              { text: "약한 아이디어는 그 팀 몫이라는 이유로 살아남지 못합니다.", color: C.red }] },
    { type: "fig", file: "silo.png",
      title: "이것이 TPA(총자산 접근)가 바꾸려는 구조입니다",
      punch: ["기준이 되는 단순한 포트폴리오를 하나 정하고, 그보다 나은 아이디어만 예산을 받습니다.",
              { text: "“이 아이디어가 기준보다 나은가”가 모든 회의의 질문이 됩니다.", color: C.red }] },
    { type: "divider", num: "04", title: "무엇이 어려운가",
      sub: "생각은 단순한데 조직을 바꾸는 일이라 어렵습니다" },
    { type: "eq", file: "equation.png", cap: "여러 아이디어를 합쳤을 때의 위험",
      title: "겹치면 위험이 더 커진다는 것을 한 줄로 적습니다",
      cards: [{ cap: "σᵢ", title: "각 베팅의 위험" },
              { cap: "ρᵢⱼ", title: "서로 겹친 정도" },
              { cap: "2Σ", title: "겹침이 더한 몫" },
              { kind: "lime", cap: "σ active", title: "전체가 진 위험" }],
      punch: [{ text: "겹침이 0이면 위험은 제곱근만큼만 늘지만, 겹치면 그대로 더해집니다.", color: C.teal },
              { text: "그래서 겹침을 볼 수 있는 눈이 TPA의 전부입니다.", color: C.red }] },
    { type: "cards", title: "이 셋만 피하면 강의가 훨씬 쉬워집니다",
      cards: [{ cap: "오해 1", title: "부서를 없앤다",
                bullets: ["없애지 않는다", "예산 주는 법을 바꾼다"] },
              { cap: "오해 2", title: "새 자산군을 산다",
                bullets: ["사는 것이 아니라", "보는 법이 바뀐다"] },
              { kind: "dark", cap: "오해 3", title: "계산 문제다",
                bullets: ["평가와 보상 문제다", "그래서 몇 년이 걸린다"] }],
      punch: [{ text: "이것은 새로운 투자 기법이 아니라, 결정을 내리는 방식의 문제입니다.", color: C.red }] },
    { type: "table", title: "이 덱의 말과 강의본의 말을 이어 둡니다",
      head: ["이 덱에서 쓴 말", "강의본이 쓰는 말", "영어"],
      rows: [["부서별 칸막이", "사일로", "silo"],
             ["기준이 되는 단순한 조합", "기준 포트폴리오", "reference portfolio"],
             ["아이디어가 받는 예산", "능동위험 예산", "active risk budget"],
             ["무엇을 졌나로 나누기", "위험요인 분해", "risk factor decomposition"],
             ["한 통에서 보는 방식", "TPA · 총자산 접근", "total portfolio approach"]],
      widths: [4.60, 3.60, 3.59], emph: 4,
      banner: "강의본은 가운데 말을 씁니다. 이 표가 둘 사이의 다리입니다." },
    { type: "table", title: "답을 맞춰 보고 강의로 넘어가십시오",
      head: ["강의 전에 답해 볼 것", "답", "왜 그런가"],
      rows: [["부서마다 잘하면 되나?", "안 된다", "겹치거나 빈 곳이 생긴다"],
             ["무엇으로 나누나?", "진 위험으로", "자산 이름으로는 겹침이 안 보인다"],
             ["가장 어려운 부분은?", "평가와 보상", "계산이 아니라 조직 문제다"]],
      widths: [4.10, 2.90, 4.79], rowH: 0.86, dy: 0.10,
      punch: [{ text: "세 개를 다 맞혔다면 종강 강의가 그대로 읽힙니다.", color: C.red }],
      punchY: 5.86, note: "※ 이 덱의 숫자는 모두 수업용으로 지어낸 예시입니다." },
    { type: "closing",
      statements: ["각자 최선을 다해도 전체는 최선이 아닐 수 있습니다.",
                   "무엇을 샀나가 아니라 무엇을 졌나로 나누면,",
                   "겹친 곳과 빈 곳이 함께 보입니다 — 이것이 TPA입니다."],
      message: "종강 강의로\n넘어가십시오",
      contacts: ["W15 · TPA 제1부 사일로 해체와 설계", "W15 · TPA 제2부 성과평가"],
      note: "※ 16주차는 캡스톤 발표와 기말시험입니다. 실제 시장 자료와 정확한 정의는 강의본과 실습데이터 덱에서 다룹니다." },
  ],
};
if (require.main === module) build(module.exports);
